Net/136db/MVC3/Controllers/CreateAccountController.cs


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC3.Models; // this is required...

namespace MVC3.Controllers
{
    public class CreateAccountController : Controller
    {
        //
        // GET: /Login/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            try
            {
                string email = collection["email"].Trim();
                string password = collection["password"].Trim();
                string first_name = collection["first_name"].Trim();
                string last_name = collection["last_name"].Trim();
                string birthDay = collection["birthDay"].Trim();
                string country = collection["country"].Trim();
                string state = collection["state"].Trim();
                string access_level = collection["access_level"].Trim();
                PLUser newUser = new PLUser();
                newUser.email = email;
                newUser.password = password;
                newUser.first_name = first_name;
                newUser.last_name = last_name;
                newUser.birthDay = birthDay;
                newUser.country = country;
                if (state == null || state == "")
                {
                    newUser.state = "NA";
                }
                else
                {
                    newUser.state = collection["state"];
                }
                newUser.access_level = access_level;
                UserClientService.InsertUser(newUser);

                return RedirectToAction("Index", "Login");
            }
            catch
            {
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult LogOff()
        {
            Session["access_level"] = null;
            Session["id"] = null;
            Session["email"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

Net/136db/MVC3/Views/CreateAccount/Index.cshtml
@model MVC3.Models.PLUser

@{
    ViewBag.Title = "Create Account";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";   
}

<h2>Create Account</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Index", "CreateAccount", FormMethod.Post, new { @class = "userdetails" }))
{
    @Html.ValidationSummary(true)
        <fieldset>
            <legend>Create Account</legend>

            <div class="editor-label">
              @ViewBag.message
            </div>
            
            <div class="editor-label">
                E-Mail :
            </div>
            <div class="editor-field">
                @Html.TextBox("email", "")
                @Html.ValidationMessageFor(model => model.email) 
            </div>

            <div class="editor-label">
                Password :
            </div>
            <div class="editor-field">
                @Html.Password("password", "")
                @Html.ValidationMessageFor(model => model.password) 
            </div>

            <div class="editor-label">
                First Name :
            </div>
            <div class="editor-field">
                @Html.TextBox("first_name", "")
                @Html.ValidationMessageFor(model => model.first_name) 
            </div>

            <div class="editor-label">
                Last Name :
            </div>
            <div class="editor-field">
                @Html.TextBox("last_name", "")
                @Html.ValidationMessageFor(model => model.last_name) 
            </div>

            <div class="editor-label">
                Birthdate :
            </div>
            <div class="editor-field">
                @Html.TextBox("birthDay", "")
                @Html.ValidationMessageFor(model => model.birthDay) 
            </div>

            <div class="editor-label">
                Country :
            </div>
            <div class="editor-field">
                @Html.TextBox("country", "")
                @Html.ValidationMessageFor(model => model.country) 
            </div>

            <div class="editor-label">
                State :
            </div>
            <div class="editor-field">
                @Html.TextBox("state", "")
                @Html.ValidationMessageFor(model => model.state) 
            </div>

            <div class="editor-label">
                Access Level [for testing] 0 = User, 1 = Admin:
            </div>
            <div class="editor-field">
                @Html.TextBox("access_level", "") 
                @Html.ValidationMessageFor(model => model.access_level) 
            </div>

            <p>
                <input type="submit" value="Create Account" />
            </p>
        </fieldset>
}